<?php
/**
 * @file
 * Provides the easy integration of the Amazon Product Advertising API.
 */


/**
 * Implements hook_theme().
 */
function amazon_theme($existing, $type, $theme, $path) {
  return [
    'amazon_inline' => [
      'variables' => ['results' => NULL],
    ],
    'amazon_image' => [
      'variables' => ['results' => NULL],
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function amazon_theme_suggestions_amazon(array $variables) {
  dsm($variables, 'in suggestions');
}

/**
 * Prepares variables for the amazon-inline Twig template.
 *
 * @param array $variables
 *   Array of variables including the results of the APA API call.
 */
function template_preprocess_amazon_inline(&$variables) {
  // Only use the first result since we only build one link.
  $variables['title'] = '';
  $variables['url'] = '';
  $variables['item'] = [];
  if (!empty($variables['results'][0])) {
    $item = $variables['results'][0];
    $variables['title'] = $item->ItemAttributes->Title;
    $variables['url'] = $item->DetailPageURL;
    $variables['item'] = $item;
  }
}

/**
 * Prepares variables for the amazon-image Twig template.
 *
 * @param array $variables
 *   Array of variables including the results of the APA API call.
 */
function template_preprocess_amazon_image(&$variables) {
  dsm($variables, 'prepro image');
}
