<?php

/**
 * @file
 * Contains amazon_field.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function amazon_field_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the amazon_field module.
    case 'help.page.amazon_field':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Allows the display of an Amazon product based on the entered ASIN.') . '</p>';
      return $output;

    default:
  }
}
